# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    
    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
    - uses: actions/checkout@v2
      # this Action should follow steps to set up Python build environment
    - name: Install Python dependencies
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install rsync zypper
        python3 -m pip install --upgrade pip
        pip install kiwi
    - name: Build image
      run: |
          sudo PYTHONPATH=$PYTHONPATH:/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages /opt/hostedtoolcache/Python/3.9.1/x64/bin/kiwi-ng \
          --profile=Virtual --type oem system build \
          --description suse/x86_64/suse-leap-15.2 \
          --target-dir /tmp/myimage
